name: macOS

on: [push]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: brew install sdl2@2.28.5 sdl2_image@2.8.2 opencv@4.8.1
      - name: Build
        run: make
