name: macOS

on: [push]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install SDL2
        run: brew install sdl2
      - name: Build
        run: make
